language: node_js
node_js: "node"

cache: yarn

install:
  - yarn install

script:
  - yarn test

deploy:
  provider: heroku
  api_key:
    secure: 617767f8-cdb2-4cae-a1c3-42f530312947 
  app: restnigeria
  on:
    repo: FunbiOyede/rest-nigeria
